version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    ports:
    - 8080:8080
    volumes:
      - .:/code
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      -CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  worker:
    build:
      context: .
      dockerfile: ./backend/worker.dockerfile
    env_file:
      - .env
    volumes:
      - .:/code

  flower:
    image: mher/flower:0.9.5
    command: [ "celery", "flower", "--broker=amqp://guest@rabbitmq:5672/", "--port=8888" ]
    ports:
      - 8888:8888
    depends_on:
      - worker
      - rabbitmq

volumes:
  db_data:
